name: test

on: [ push ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-14', 'macos-13']
        perl: [ '5.38', '5.36', '5.34', '5.32', '5.30' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - uses: actions/checkout@v4
      - name: Install Toolchain
        run: cpanm -q -n --no-man-pages App::cpm
      - name: Install Test2::Harness
        run: cpm install -g Test2::Harness
      - name: Install Dependencies
        run: cpm install -g
      - name: yath
        run: yath test --qvf
